### ISSUE TITLE
Insufficient check on `set!`

### ISSUE THREAD

**Issue by okuoku** [okuoku/rapid-gambit#5]
`set!` with wrong syntax yields cryptic error message:

``` scheme
(import (scheme base))

(define a 0)

(set! (begin a) a)
```

Results

```
/opt/rapid-gambit/bin/rapid-gambit: internal error
*** ERROR IN abort -- not a record
(#<<record> #2 fields: #(#<<record> #3 fields: #(<syntax> #<<record>
```

At https://github.com/okuoku/rapid-gambit/commit/ac88aa025670cbd1cc5e92e5c9884258c85979cd

**Comment by mnieper** [comment]
This is an error in the Rapid expander. Investigating.

**Comment by mnieper** [comment]
Fixed upstream.

https://gitlab.com/nieper/rapid-scheme/commit/bf5f51f0398d4b2b3c1becb66e96096c2b248806

**Comment by okuoku** [comment]
Thank you for the patch! Landed in https://github.com/okuoku/rapid-gambit/commit/60023da8dcc860d24b26c7923ce617e23f12fbb4
